on: push
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: $CONDA/bin/conda env update --file environment.yml --name base
    - if: ${{ always() }}
      name: Problem 1.1
      run: $CONDA/bin/pytest -k prob1_1 test.py
    - if: ${{ always() }}
      name: Problem 1.2
      run: $CONDA/bin/pytest -k prob1_2 test.py
    - if: ${{ always() }}
      name: Problem 1.3
      run: $CONDA/bin/pytest -k prob1_3 test.py

# on: push
# jobs:
#   build:
#     name: Generate Exam
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repo
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Create Personalized Exam
#       run: python make_dumb_exam.py
#     - name: commit files
#       run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git add -A
#         git commit -m "Create Exam"
#     - name: Push changes
#       uses: ad-m/github-push-action@v0.6.0
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: main
        
